# Generated by Django 2.1.5 on 2019-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('event_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('cust_num', models.IntegerField(default=8)),
                ('case_stat', models.CharField(max_length=100)),
                ('case_num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
