# Generated by Django 2.2a1 on 2019-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrt_app', '0002_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cust_num',
            field=models.CharField(max_length=100),
        ),
    ]
