# Generated by Django 2.1.7 on 2019-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrt_app', '0003_auto_20190210_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coordinates',
            field=models.CharField(default='[-73.98513, 40.758896]', max_length=1000),
        ),
    ]
