# Generated by Django 2.2a1 on 2019-02-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrt_app', '0003_auto_20190210_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coordinates',
            field=models.CharField(default='[-73.98513, 40.758896]', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=models.CharField(max_length=500), max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
