# Generated by Django 2.2a1 on 2019-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrt_app', '0004_auto_20190224_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='case_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
