# Generated by Django 2.1.7 on 2019-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrt_app', '0005_auto_20190226_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='device',
            field=models.CharField(default='desktop', max_length=100),
        ),
    ]
